Fv = 0.0025;    % Viscous friction factor in drive line
Kb = 0.0255;    % Back EMF Constant
Kt = 0.0255;    % Torque Constant
Mc = 1.59;      % Mass of robot body
Mw = 0.133;     % Mass of robot wheel
m = Mc+3*Mw;    % Total mass of robot
r = 0.03;       % Radius of each whee;
L = 0.1255;     % Distance b/w centre of robot and each wheel
Jw = Mw*(r^2)/4;% Inertia of wheel
Jc = Mc*(L^2)/2;% Inertia of Robot body
J = 3*Jw + Jc;  % Total Inertia
Vs = 24;        % Battery Voltage
tw = 0.045;     % ???
Ra = 7.9;       % Armature Resistance
n = 3;          % ASSUMED Gear Ratio

x_f = 0.5;      % Final x-coordinate
tf = 1;         % Final time
psi_f = pi;     % Final heading in GCS
psi = 0;        % Initial heading in GCS